# file: .github/workflows/show-directory.yml
name: start
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      - name: Print Hello from Hexlet
      - uses: hexlet-components/hello-from-hexlet-action@release
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm' 
      # run – произвольная bash-команда
      - run: make setup
      - run: make test 
      - run: make lint 